#!/usr/bin/env bash

# setup args
function processConfig() {
    source src/validateArgs
    source src/getIncludeString
    source src/appendLineToFile
    source src/removeLineFromFile

    aux_placeholder="aauuxx__ccoonnff"
    template="$1"
    aux="$2"
    main_config="$3"
    remove="$4"

    validateArgs "$aux_placeholder" "${@}"

    insert_string="$(getIncludeString "$template" "$aux" "$aux_placeholder")"

    if [ "$remove" == True ]; then
        removeLineFromFile "$insert_string" $main_config
    else
        appendLineToFile "$insert_string" $main_config
    fi
}
