#!/usr/bin/env bash

# setup args
function processConfig() {
    source src/validateArgs
    source src/getIncludeString
    source src/appendLineToFile

    aux_placeholder="aauuxx__ccoonnff"
    template="$1"
    aux="$2"
    main_config="$3"

    echo "${@}"
    validateArgs "$aux_placeholder" "${@}"

    insert_string="$(getIncludeString "$template" "$aux" "$aux_placeholder")"

    appendLineToFile "$insert_string" $main_config
}
